### ISSUE TITLE
Puzzle that bridges-solver fails to solve

### ISSUE THREAD

**Issue by ajwans** [tonivrbic/bridges-solver#2]
Here is a puzzle which is solvable but the algorithm fails to solve.

```
const puzzle = [                  
  [0, 2, 0, 0, 4, 0, 0, 3, 0, 3 ],
  [2, 0, 0, 2, 0, 0, 4, 0, 2, 0 ],
  [0, 1, 0, 0, 0, 0, 0, 1, 0, 3 ],
  [3, 0, 0, 0, 3, 0, 5, 0, 1, 0 ],
  [0, 3, 0, 5, 0, 0, 0, 2, 0, 4 ],
  [0, 0, 0, 0, 0, 0, 2, 0, 1, 0 ],
  [3, 0, 1, 0, 3, 0, 0, 1, 0, 0 ],
  [0, 2, 0, 4, 0, 1, 0, 0, 0, 3 ],
  [0, 0, 0, 0, 2, 0, 3, 0, 2, 0 ],
  [2, 0, 0, 4, 0, 3, 0, 2, 0, 2 ],
];
```

**Comment by tonivrbic** [comment]
Could you please send me the right steps to solve this puzzle?

**Comment by ajwans** [comment]
The key insight is around row 7, column 5. The 1-circle there has 3 neighbours.  

- If it connects to it's left neighbour (7,3), then an island chain would be formed by (8,4) = (8,6) - (8,8) - (5,8).
- If it connects to it's bottom neighbour (9,5) then there are two possibilities:
  a. (8,6) = (8,8) but this is not possible because then (8,6) - (5,6) - (5,8) forms an island chain
  b. (8,6) = (5,6) but this is not possible because then (8,6) - (8,8) - (5,8) forms an island chain

This leaves (7,5) - (7,9) as the only possibility.

There were other deductions needed to solve this particular problem but they all essentially boiled down to the "all circles must be connected" rule.

**Comment by tonivrbic** [comment]
I've published a new version of this library that should solve your puzzle. The version is 1.1.0 and is available on npm. 
This new version tries with brute force to find a possible connection, so it might take a few seconds longer for very hard puzzles (like this one).
